[package]
name = "RustyWordle"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.1"
serde_json = "1.0.124"
rayon = "1.10.0"
rand = "0.8.5"
eframe = "0.28.1"
reqwest = {version="0.12.5", features=["blocking"]}
tokio = { version="1", features=["full"]}
